# Dockerイメージのビルド
docker build -t shiworks/tippecanoe-gdal:latest .

# ビルドしたイメージのテスト
docker run -it shiworks/tippecanoe-gdal:latest bash

exit

# Docker Hubにイメージをプッシュ
docker login
docker push shiworks/tippecanoe-gdal:latest